import { useEffect, useMemo, useState } from 'react';
import { createClient, type User } from '@supabase/supabase-js';
import { ArrowDown, ArrowUpRight, CheckCircle2, CircleHelp, Clock3, Code2, Download, Globe2, History, LogIn, LogOut, Rocket, ShieldCheck, Smartphone, Sparkles, Terminal, WandSparkles, XCircle } from 'lucide-react';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://upajzbaeuwzbhxfebzvi.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_tvp9Kreo5aMpK-aEU3AteA_axQbYhDP';
const supabase = createClient(supabaseUrl, supabaseKey);
type Build = { id:string; status:string; requested_at:string; apk_url:string|null; aab_url:string|null; source_zip_url:string|null; error_message:string|null; projects?:{name:string;website_url:string;package_name:string}|null };
type Profile = {role:string; display_name:string|null};
const statusText: Record<string,string> = {pending:'Queued',building:'Building',completed:'Ready',failed:'Failed'};
function validUrl(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password}catch{return false}}
function App(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState<'signin'|'signup'>('signin'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[builds,setBuilds]=useState<Build[]>([]),[loadingBuilds,setLoadingBuilds]=useState(false);
 const [name,setName]=useState('My Website'),[website,setWebsite]=useState('https://example.com'),[pkg,setPkg]=useState('com.example.mywebsite'),[iconUrl,setIconUrl]=useState(''),[splash,setSplash]=useState('#111827');
 const [tab,setTab]=useState<'create'|'history'|'admin'>('create');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?.user??null));return()=>subscription.unsubscribe()},[]);
 async function loadProfile(u:User){const {data}=await supabase.from('profiles').select('role,display_name').eq('id',u.id).maybeSingle();setProfile(data as Profile|null)}
 useEffect(()=>{if(user){void loadProfile(user);void loadBuilds()}else{setProfile(null);setBuilds([])}},[user]);
 async function loadBuilds(){if(!user)return;setLoadingBuilds(true);const {data,error}=await supabase.from('builds').select('id,status,requested_at,apk_url,aab_url,source_zip_url,error_message,projects(name,website_url,package_name)').order('requested_at',{ascending:false}).limit(30);if(error)setNotice(error.message);else setBuilds((data??[]) as unknown as Build[]);setLoadingBuilds(false)}
 async function authSubmit(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');try{const result=authMode==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)throw result.error;setNotice(authMode==='signup'?'Account created. If email confirmation is enabled, check your inbox.':'Signed in successfully.')}catch(e){setNotice(e instanceof Error?e.message:'Authentication failed')}finally{setBusy(false)}}
 async function signOut(){await supabase.auth.signOut();setNotice('You have signed out.')}
 async function submitBuild(e:React.FormEvent){e.preventDefault();if(!user){setNotice('Sign in first to request an Android build.');return}if(!validUrl(website)){setNotice('Enter a valid HTTP(S) website URL.');return}if(!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(pkg)){setNotice('Package name must look like com.example.app');return}setBusy(true);setNotice('');try{const {data:{session}}=await supabase.auth.getSession();const {data,error}=await supabase.functions.invoke('request-build',{body:{name,website_url:website,package_name:pkg,icon_url:iconUrl||null,splash_color:splash},headers:{Authorization:'Bearer '+session?.access_token}});if(error)throw error;if(data?.error)throw new Error(data.error);setNotice('Build queued! Your build ID is '+data.build_id);setTab('history');await loadBuilds()}catch(e){setNotice(e instanceof Error?e.message:'Could not submit build request')}finally{setBusy(false)}}
 const counts=useMemo(()=>({all:builds.length,ready:builds.filter(b=>b.status==='completed').length,running:builds.filter(b=>['pending','building'].includes(b.status)).length}),[builds]);
 useEffect(()=>{if(!user)return;const timer=window.setInterval(()=>{void loadBuilds()},12000);return()=>window.clearInterval(timer)},[user]);
 return <div className="min-h-screen text-slate-100">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
   <a href="#" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-violet-300 text-slate-950"><WandSparkles size={22}/></div><div><div className="text-lg font-black tracking-[.18em]">MEGA</div><div className="text-[10px] uppercase tracking-[.22em] text-slate-500">Web to Android</div></div></a>
   <div className="flex items-center gap-3">{user?<><span className="hidden text-sm text-slate-400 sm:block">{user.email}</span><button className="btn btn-quiet text-sm" onClick={signOut}><LogOut size={16}/> Sign out</button></>:<a href="#account" className="btn btn-quiet text-sm"><LogIn size={16}/> Sign in</a>}</div>
  </header>
  <main className="grid-bg">
   <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-12 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:pb-24 lg:pt-20">
    <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-300/10 px-3 py-2 text-xs font-semibold text-violet-200"><Sparkles size={14}/> FREE BUILDS · OPEN SOURCE OUTPUT</div>
     <h1 className="max-w-3xl text-5xl font-black leading-[1.05] tracking-[-.055em] sm:text-6xl lg:text-7xl">Your website.<br/><span className="bg-gradient-to-r from-violet-200 via-violet-400 to-sky-300 bg-clip-text text-transparent">An Android app.</span></h1>
     <p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">Turn any website into a downloadable Android app package. Build APK, AAB and the complete Android source project from one simple dashboard.</p>
     <div className="mt-8 flex flex-wrap gap-3"><a href="#builder" className="btn btn-primary">Build your app <ArrowDown size={17}/></a><a href="#how" className="btn btn-quiet">How it works <ArrowUpRight size={17}/></a></div>
     <div className="mt-10 flex flex-wrap gap-2"><span className="pill flex items-center gap-2"><CheckCircle2 size={14}/> APK download</span><span className="pill flex items-center gap-2"><CheckCircle2 size={14}/> AAB package</span><span className="pill flex items-center gap-2"><Code2 size={14}/> Source ZIP</span></div>
    </div>
    <div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-6 rounded-[3rem] bg-violet-500/10 blur-3xl"/><div className="glass relative rounded-[2.5rem] p-4 shadow-glow"><div className="rounded-[2rem] border border-slate-700/70 bg-[#0a0f1c] p-5"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-2"><div className="h-2 w-2 rounded-full bg-emerald-400"/><span className="text-xs text-slate-400">BUILD ENVIRONMENT</span></div><span className="pill">v1.0</span></div><div className="mx-auto flex h-56 w-40 flex-col items-center justify-center rounded-[2rem] border-[5px] border-slate-700 bg-gradient-to-br from-violet-500/20 to-sky-500/10"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-300 text-slate-950"><Globe2 size={34}/></div><div className="text-sm font-bold">Your Website</div><div className="mt-1 text-[10px] text-slate-500">Now on Android</div><div className="mt-7 h-1 w-12 rounded-full bg-slate-600"/></div><div className="mt-6 space-y-3">{[['APK','Installable Android app'],['AAB','Play Store bundle'],['SOURCE ZIP','Editable project']].map(([t,d])=><div key={t} className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-900/70 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-300/10 text-violet-200"><Code2 size={17}/></div><div className="flex-1"><div className="text-xs font-bold">{t}</div><div className="text-[11px] text-slate-500">{d}</div></div><CheckCircle2 size={16} className="text-emerald-400"/></div>)}</div></div></div></div>
   </section>
   <section id="builder" className="mx-auto grid max-w-7xl gap-6 px-5 pb-20 lg:grid-cols-[.72fr_1.28fr] lg:px-8">
    <aside className="glass h-fit rounded-3xl p-5"><div className="mb-5 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-300/10 text-violet-200"><Smartphone size={22}/></div><div><h2 className="font-bold">Build workspace</h2><p className="text-xs text-slate-500">Your projects, in one place</p></div></div>
     <div className="space-y-2">{([{id:'create',label:'Create an app',icon:<Rocket size={17}/>},{id:'history',label:'Build history',icon:<History size={17}/>},...(profile?.role==='admin'?[{id:'admin',label:'Admin overview',icon:<ShieldCheck size={17}/>}]:[])] as {id:string;label:string;icon:React.ReactNode}[]).map(t=><button key={t.id} onClick={()=>{setTab(t.id as typeof tab);if(t.id==='history')void loadBuilds()}} className={'flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm '+(tab===t.id?'bg-violet-300/10 font-semibold text-violet-200':'text-slate-400 hover:bg-white/5 hover:text-white')}>{t.icon}{t.label}</button>)}</div>
     <div className="mt-6 grid grid-cols-3 gap-2">{[['Builds',counts.all],['Ready',counts.ready],['In queue',counts.running]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="text-xl font-bold">{value}</div><div className="mt-1 text-[10px] text-slate-500">{label}</div></div>)}</div>
     <div className="mt-5 rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><CircleHelp size={16} className="text-violet-200"/> Free tier policy</div><p className="mt-2 text-xs leading-5 text-slate-500">Up to 5 build requests per account every 24 hours. Builds run on GitHub Actions usage quotas.</p></div>
    </aside>
    <div className="glass min-w-0 rounded-3xl p-5 sm:p-7">
     {!user?<div id="account" className="mx-auto max-w-md py-8"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-300/10 text-violet-200"><LogIn size={23}/></div><h2 className="text-2xl font-bold">{authMode==='signin'?'Welcome back':'Create your account'}</h2><p className="mt-2 text-sm text-slate-400">Sign in to submit builds and access your downloads.</p><form onSubmit={authSubmit} className="mt-6 space-y-4"><label className="block text-sm text-slate-300">Email<input className="field mt-2" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="block text-sm text-slate-300">Password<input className="field mt-2" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button disabled={busy} className="btn btn-primary w-full disabled:opacity-50">{busy?'Please wait…':authMode==='signin'?'Sign in':'Create account'} <ArrowUpRight size={17}/></button></form><button onClick={()=>setAuthMode(authMode==='signin'?'signup':'signin')} className="mt-4 text-sm text-violet-200 hover:underline">{authMode==='signin'?'New here? Create an account':'Already registered? Sign in'}</button></div>
     :tab==='create'?<><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-200">App configuration</div><h2 className="mt-2 text-2xl font-bold">Create your Android app</h2><p className="mt-2 text-sm text-slate-400">Configure the website and start a cloud build.</p></div><span className="pill flex shrink-0 items-center gap-1"><Sparkles size={13}/> Free</span></div>
      <form onSubmit={submitBuild} className="mt-7 space-y-5"><label className="block text-sm font-medium text-slate-300">Website URL<input className="field mt-2" type="url" required value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://yourwebsite.com"/><span className="mt-1 block text-xs text-slate-500">The website must allow loading inside a WebView.</span></label>
       <div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-300">App name<input className="field mt-2" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="My Website"/></label><label className="block text-sm font-medium text-slate-300">Package name<input className="field mt-2" required value={pkg} onChange={e=>setPkg(e.target.value)} placeholder="com.example.app"/></label></div>
       <label className="block text-sm font-medium text-slate-300">App icon URL <span className="text-slate-600">(optional)</span><input className="field mt-2" type="url" value={iconUrl} onChange={e=>setIconUrl(e.target.value)} placeholder="https://example.com/icon.png"/><span className="mt-1 block text-xs text-slate-500">Icon URL is saved for future icon injection; the initial template uses the default Android icon.</span></label>
       <label className="block text-sm font-medium text-slate-300">Splash / system bar color<div className="mt-2 flex gap-3"><input type="color" value={splash} onChange={e=>setSplash(e.target.value)} className="h-11 w-14 rounded-lg border border-slate-700 bg-slate-900 p-1"/><input className="field" value={splash} onChange={e=>setSplash(e.target.value)} pattern="^#[0-9a-fA-F]{6}$"/></div></label>
       <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 text-xs leading-5 text-slate-400"><ShieldCheck size={15} className="mr-2 inline text-emerald-300"/> Requests are tied to your account. Build status and download links are only visible to you and authorized administrators.</div>
       <button disabled={busy} className="btn btn-primary w-full disabled:cursor-not-allowed disabled:opacity-50">{busy?'Submitting build…':'Generate Android app'} <Rocket size={17}/></button>
      </form></>
     :tab==='history'?<><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-200">Activity</div><h2 className="mt-2 text-2xl font-bold">Build history</h2></div><button className="btn btn-quiet text-xs" onClick={()=>void loadBuilds()}><History size={15}/> Refresh</button></div><p className="mt-2 text-sm text-slate-400">Status refreshes automatically every 12 seconds.</p><div className="mt-6 space-y-3">{loadingBuilds&&!builds.length?<p className="py-8 text-center text-sm text-slate-500">Loading build history…</p>:builds.length===0?<div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center"><Terminal className="mx-auto text-slate-500" size={28}/><p className="mt-3 font-semibold">No builds yet</p><p className="mt-1 text-sm text-slate-500">Create your first Android app to see it here.</p><button className="btn btn-primary mt-4" onClick={()=>setTab('create')}>Create an app</button></div>:builds.map(b=><div key={b.id} className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{b.projects?.name??'Android build'}</div><div className="mt-1 max-w-sm truncate text-xs text-slate-500">{b.projects?.website_url??b.id}</div><div className="mt-2 text-[11px] text-slate-600">{new Date(b.requested_at).toLocaleString()}</div></div><span className={'pill flex items-center gap-1 '+(b.status==='completed'?'text-emerald-300':b.status==='failed'?'text-rose-300':'text-amber-200')}>{b.status==='completed'?<CheckCircle2 size={13}/>:b.status==='failed'?<XCircle size={13}/>:<Clock3 size={13}/>} {statusText[b.status]??b.status}</span></div>{b.error_message&&<p className="mt-3 rounded-lg bg-rose-500/10 p-3 text-xs text-rose-200">{b.error_message}</p>}{b.status==='completed'&&<div className="mt-4 flex flex-wrap gap-2">{[[b.apk_url,'APK'],[b.aab_url,'AAB'],[b.source_zip_url,'Source ZIP']].filter(([url])=>url).map(([url,label])=><a key={label as string} className="btn btn-quiet text-xs" href={url as string} target="_blank" rel="noreferrer"><Download size={14}/>{label as string}</a>)}</div>}</div>)}</div></>
     :<><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-200">Administration</div><h2 className="mt-2 text-2xl font-bold">Platform overview</h2><p className="mt-2 text-sm text-slate-400">Admin role detected. All-build management and log inspection can be extended here without bypassing RLS.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['All visible builds',counts.all],['Completed',counts.ready],['In progress',counts.running]].map(([t,n])=><div className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4" key={t}><div className="text-2xl font-bold">{n}</div><div className="mt-1 text-xs text-slate-500">{t}</div></div>)}</div><p className="mt-4 text-xs text-slate-500">To grant admin access, update your own profile role through the Supabase SQL Editor. Never expose the service-role key in this frontend.</p></>}
     {notice&&<div className="mt-5 flex items-start gap-2 rounded-xl border border-violet-300/20 bg-violet-300/10 p-3 text-sm text-violet-100"><CircleHelp className="mt-0.5 shrink-0" size={16}/><span className="flex-1 break-words">{notice}</span><button onClick={()=>setNotice('')} aria-label="Dismiss"><XCircle size={16}/></button></div>}
    </div>
   </section>
   <section id="how" className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="mb-8 text-center"><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-200">Simple by design</div><h2 className="mt-3 text-3xl font-bold">From URL to Android</h2></div><div className="grid gap-4 md:grid-cols-3">{[{n:'01',title:'Configure',desc:'Enter your website URL, app name and Android package ID.'},{n:'02',title:'Build in the cloud',desc:'GitHub Actions generates an Android WebView project and compiles the packages.'},{n:'03',title:'Download',desc:'Get the APK, AAB and editable Android source ZIP from your build history.'}].map(x=><div key={x.n} className="glass rounded-2xl p-6"><div className="text-sm font-bold text-violet-200">{x.n}</div><h3 className="mt-4 text-lg font-bold">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{x.desc}</p></div>)}</div></section>
  </main>
  <footer className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-7 text-xs text-slate-600 lg:px-8"><span>© {new Date().getFullYear()} MEGA · Website to Android</span><span className="flex items-center gap-2"><ShieldCheck size={14}/> Supabase protected · GitHub Actions builds</span></footer>
 </div>
}
export default App;
